package es.rf.tienda.util;

public class Creacion {

	final String CREATE_PRODUCTO = 
			"CREATE TABLE 'ALUMNO'.'PRODUCTOS' " +
					"(	'ID_PRODUCTO' VARCHAR2(5 BYTE) NOT NULL ENABLE, "+
					"'PRO_DESCRIPCION' VARCHAR2(100 BYTE) NOT NULL ENABLE, "+
					" 'PRO_DESLARGA' VARCHAR2(2000 BYTE), "+
					" 'PRO_PRECIO' NUMBER(3,2), "+
					" 'PRO_STOCK' NUMBER(*,0), "+
					" 'PRO_FECREPOS' DATE, "+
					" 'PRO_FECACTI' DATE, "+
					" 'PRO_FECDESACTI' DATE,"+ 
					" 'PRO_UNIVENTA' VARCHAR2(20 BYTE),"+ 
					" 'PRO_CANTXUNIVENTA' NUMBER(5,2), "+
					" 'PRO_UNIULTNIVEL' VARCHAR2(20 BYTE),"+ 
					" 'ID_PAIS' NUMBER(*,0), "+
					" 'PRO_USORECOMENDADO' VARCHAR2(2000 BYTE),"+ 
					" 'ID_CATEGORIA' NUMBER(*,0), "+
					" 'PRO_STKRESERVADO' NUMBER(*,0),"+ 
					" 'PRO_NSTKALTO' NUMBER(5,2), "+
					" 'PRO_NSTKBAJO' NUMBER(5,2), "+
					" 'PRO_STAT' CHAR(1 BYTE), "+
					
		 		" CONSTRAINT 'PRODUCTOS_PK' PRIMARY KEY ('ID_PRODUCTO')"+
		 		" USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 " +
		 		" STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645"+
		 		" PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)"+
		 			
		 		" TABLESPACE 'SYSTEM'  ENABLE"+
			    " ) SEGMENT CREATION IMMEDIATE "+
			    " PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING"+
			    " STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645"+
			    " PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)"+
			    " TABLESPACE 'SYSTEM'" ;
	final String CREATE_PRODUCTO_INDEX1 = 
			" CREATE INDEX 'ALUMNO'.'PRO_IDPAIS' ON 'ALUMNO'.'PRODUCTOS' ('ID_PAIS') "+
					" PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS "+
					" STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 "+
					" PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)"+
					" TABLESPACE 'SYSTEM' ";
	
	final String CREATE_PRODUCTO_INDEX2 = 
			" CREATE INDEX 'ALUMNO'.'PRO_ID_CATEGORIA' ON 'ALUMNO'.'PRODUCTOS' ('ID_CATEGORIA')"+ 
					" PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS"+ 
					" STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645"+
					" PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)"+
					" TABLESPACE 'SYSTEM' ";

	  
	  
	  final String CREATE_ALUMNO = 
			  " CREATE TABLE 'ALUMNO'.'CATEGORIAS'"+ 
					  " (	'ID_CATEGORIA' NUMBER(*,0) NOT NULL ENABLE,"+
					  " 'CAT_NOMBRE' VARCHAR2(50 BYTE),"+ 
					  " 'CAT_DESCRIPCION' VARCHAR2(200 BYTE),"+ 
					  	" CONSTRAINT 'CATEGORIAS_PK' PRIMARY KEY ('ID_CATEGORIA')"+
					  		" USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255"+ 
					  		" STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645"+
					  		" PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)"+
					  		" TABLESPACE 'SYSTEM'  ENABLE"+
					  		" ) SEGMENT CREATION IMMEDIATE"+ 
	  						" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING"+
	  						" STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645"+
	  						" PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)"+
	  						" TABLESPACE 'SYSTEM' ";



	  public static void crearBD(){
		  
	  }
}


